"""add reader table and relation

Revision ID: 1ec4c68680a3
Revises: f4020277e176
Create Date: 2023-02-28 17:00:44.640707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec4c68680a3'
down_revision = 'f4020277e176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.add_column('books', sa.Column('reader_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'readers', ['reader_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'reader_pk')
    op.drop_table('readers')
    # ### end Alembic commands ###
