"""fix missing comma

Revision ID: 55707ab821b6
Revises: 81fe70c5b62e
Create Date: 2023-02-14 14:07:38.262140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55707ab821b6'
down_revision = '81fe70c5b62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'just_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('just_test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
