"""create book model

Revision ID: b5911adcf28c
Revises: 
Create Date: 2023-02-14 13:08:47.996497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5911adcf28c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('other', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
